# Generated by Django 5.2.1 on 2025-05-25 21:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nameType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EcoPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('openingHours', models.CharField(max_length=100)),
                ('imageUrl', models.URLField()),
                ('isMunicipal', models.BooleanField(default=False)),
                ('wasteTypes', models.ManyToManyField(to='ecopoints.wastetype')),
            ],
        ),
    ]
